----CREATE WITH AS
    CREATE TABLE t
    AS 
    WITH some_data AS ( 
       SELECT 1 as some_value 
       FROM dual

       UNION ALL 

       SELECT 2 
       FROM dual
    ) 
    SELECT * 
    FROM some_data
;
CREATE TABLE QUERIES
( 
  DB_TYPE VARCHAR2(30) NOT NULL,
  DB_NAME VARCHAR2(30) NOT NULL,
  QUERY_NAME VARCHAR2(100) NOT NULL,
  QUERY VARCHAR2(3999) NOT NULL,
  CREATE_DATE DATE NOT NULL,
  QUERY_DEFINITION VARCHAR2(2000) NOT NULL,
  PRODUCT_NAME VARCHAR2(50) NOT NULL,
  PERIOD VARCHAR(1) NOT NULL,
  DAY_NUM NUMBER NOT NULL
)
;
CREATE TABLE STAT_RESULTS
( 
PROCESS_DATE DATE NOT NULL,
YEARMONTH NUMBER NOT NULL,
QUERY_NAME VARCHAR2(100) NOT NULL,
STAT_RESULT NUMBER NOT NULL
);

CREATE TABLE FIZY_PACKAGES
( 
    PACKAGE_TYPE VARCHAR2(50),
    PACKAGE_ID	NUMBER(22),
    PACKAGE_NAME	VARCHAR2(512),
    PACKAGE_NK	VARCHAR2(512),
    OFFER_ID	VARCHAR2(512),
    SOURCE_SYSTEM_SK	NUMBER(22),
    INSERT_DATE DATE NOT NULL
)
;
CREATE TABLE MO_Kontrat_Bitis
( 
  IMPORT_DATE DATE,
  ALLOW_STATUS VARCHAR2(30),
  YEARMONTH NUMBER,
  SUBSCRIBER_ID NUMBER
)
;

SELECT * FROM TCMEYGI.QUERIES;
SELECT * FROM TCMEYGI.STAT_RESULTS;

SELECT * FROM TCMEYGI.QUERIES WHERE PRODUCT_NAME ='FIZY'
ORDER BY QUERY_NAME ;

SELECT aa.*,bb.QUERY_DEFINITION 
FROM TCMEYGI.STAT_RESULTS aa, TCMEYGI.QUERIES bb
WHERE aa.QUERY_NAME = bb.QUERY_NAME
    and bb.PRODUCT_NAME ='FIZY'
order by aa.PROCESS_DATE desc
;
--TABLO DROP ETME
DROP TABLE STAT_RESULTS;

--USERLARA SELECT-INSERT-DELETE-UPDATE YETKISI VERME
--TCMECETINER,TCEKIVRAK,TCHAYILMAZ,TCBTALAYMAN,TCMUDEMIRCI,TCOYUCEER
GRANT UPDATE ON TCMEYGI.QUERIES TO TCMECETINER,TCEKIVRAK,TCHAYILMAZ,TCGCINAR,TCMUDEMIRCI,TCOYUCEER ;
GRANT INSERT, SELECT, UPDATE ON TCMEYGI.QUERIES TO TCEKIVRAK
;
GRANT SELECT ON TCMEYGI.ESRA_fizy_SA_MAU2 TO TCMECETINER,TCOYUCEER
;
GRANT SELECT ON TCMEYGI.FIZY_PACKAGES TO TCEKIVRAK
;
--Yaratýlan (senin dahil olduðun ve yarattýðýn) tablolarda kimde ne yetkisi var  bu komut ile gözüküyor.
select * from USER_TAB_PRIVS
where owner='TCOYUCEER' --and privilege = 'INSERT'
--group by table_name
;
select *

--- INSERT TABLE INFOINSERT INTO QUERIES
INSERT INTO TCMEYGI.QUERIES
(DB_TYPE,DB_NAME,QUERY_NAME,QUERY,CREATE_DATE,QUERY_DEFINITION,PRODUCT_NAME,PERIOD,DAY_NUM
 )
VALUES
('ORACLE', 
'XDDS',	
'FIZY_COUNT_KK_STORE_RETENTION',
'--QUERY BU KISMA GELECEK',
TRUNC(SYSDATE),
'FIZY kredikartý-store abone retention',
'FIZY',
'D',
1
)
;
SELECT * FROM TCMEYGI.QUERIES WHERE QUERY_NAME LIKE '%365%' OR QUERY_NAME LIKE '%90%';

SELECT * FROM TCMEYGI.QUERIES WHERE QUERY_DEFINITION IS NULL --  'FIZY ayný gün%' 
;
DELETE FROM TCMEYGI.QUERIES WHERE QUERY_DEFINITION IS NULL ;
DELETE FROM TCMEYGI.QUERIES WHERE QUERY_NAME = 'TVPLUS_COUNT_ACQ_STORE' ;

SELECT * FROM TCMEYGI.STAT_RESULTS ; 

DELETE FROM TCMEYGI.STAT_RESULTS WHERE QUERY_NAME = 'ASD';
DELETE FROM TCMEYGI.STAT_RESULTS ;
ALTER TABLE TCMEYGI.QUERIES ADD PRODUCT_NAME VARCHAR2(50);

-- COLUMN DROP ETME 
ALTER TABLE TCMEYGI.STAT_RESULTS_BACKUP DROP COLUMN STAT_TYPE
;

DELETE FROM TCMEYGI.QUERIES WHERE QUERY LIKE '--store kk%' ;

TRUNCATE TABLE TABLE_NAME; --TABLO ÝÇERÝSÝNDEKÝ BÜTÜN RECORDLARI SÝLER. DELETE FROM TABLE_NAME ÝLE AYNI.

select * from TCMEYGI.QUERIES WHERE QUERY_NAME LIKE 'LIFEBOX%' ; 


--update value
UPDATE TCMEYGI.QUERIES SET DAY_NUM = 1  ;--WHERE QUERY_NAME LIKE 'LIFEBOX%'


SELECT * FROM TCMEYGI.QUERIES ;
ALTER TABLE TCMEYGI.QUERIES MODIFY ("PERIOD" NOT NULL ENABLE) ;

COMMIT;

--XDDS altýnaki yetki görünümüm.
select * from USER_ROLE_PRIVS;

--Yaratýlan (senin dahil olduðun ve yarattýðýn) tablolarda kimde ne yetkisi var  bu komut ile gözüküyor.
select * from USER_TAB_PRIVS;
--Bu komut boþ döndü :)
select * from USER_SYS_PRIVS;


SELECT * FROM TCMEYGI.STAT_RESULTS
WHERE  TO_DATE(PROCESS_DATE) = TO_DATE(SYSDATE)
;

DELETE FROM TCMEYGI.STAT_RESULTS
WHERE  TO_DATE(PROCESS_DATE) = TO_DATE(SYSDATE);

SELECT * FROM TCMEYGI.STAT_RESULTS
WHERE  TO_DATE(PROCESS_DATE) = TO_DATE(SYSDATE)
;

SELECT R1.*,R2.STAT_RESULT AS DUN
FROM 
    (--BUGÜN
    SELECT * FROM TCMEYGI.STAT_RESULTS 
    WHERE TRUNC(PROCESS_DATE)=TRUNC(SYSDATE)
    ORDER BY 3 ASC,1 DESC
    ) R1,
    (--DÜN
    SELECT * FROM TCMEYGI.STAT_RESULTS 
    WHERE TRUNC(PROCESS_DATE)=TRUNC(SYSDATE-1)
    ORDER BY 3 ASC,1 DESC
    ) R2
WHERE R1.QUERY_NAME = R2.QUERY_NAME

;

SELECT DB_TYPE, DB_NAME, QUERY_NAME, CREATE_DATE, QUERY_DEFINITION, PRODUCT_NAME, PERIOD, DAY_NUM,QUERY FROM (
SELECT DB_TYPE, DB_NAME, QUERY_NAME, QUERY, CREATE_DATE, QUERY_DEFINITION, PRODUCT_NAME, PERIOD, DAY_NUM, ROW_NUMBER() OVER (PARTITION BY QUERY_NAME ORDER BY CREATE_DATE DESC) ROW_NUM
FROM TCMEYGI.QUERIES )
WHERE ROW_NUM = 1 AND QUERY_NAME LIKE 'FIZY%' AND QUERY_NAME LIKE '%CLOSING%'
--AND PRODUCT_NAME = 'FIZY'
--AND (QUERY_NAME LIKE '%KK%' OR QUERY_NAME LIKE '%STORE%') 
;

SELECT QUERY_NAME,
    INSTR(QUERY_NAME, '_'),
    SUBSTR(QUERY_NAME,1,INSTR(QUERY_NAME, '_')) AS A1,
    SUBSTR(QUERY_NAME,INSTR(QUERY_NAME, '_')+7) AS A2,
    SUBSTR(QUERY_NAME,1,INSTR(QUERY_NAME, '_')) || SUBSTR(QUERY_NAME,INSTR(QUERY_NAME, '_')+7) NEW_QUERY_NAME,
    SUBSTR(QUERY_NAME,INSTR(QUERY_NAME, '_')+1,INSTR(QUERY_NAME, '_')-1) AS QUERY_TYPE
    
 
FROM TCMEYGI.QUERIES 

;
SELECT * FROM TCMEYGI.QUERIES
WHERE QUERY_NAME = 'TVPLUS_COUNT_ACT_STORE_MAU'

;
SELECT * FROM TCMEYGI.STAT_RESULTS
WHERE QUERY_NAME = 'TVPLUS_COUNT_ACT_STORE_MAU'
order by 1 desc
;
-------INSERT STAT_RESULTS------
INSERT INTO TCMEYGI.STAT_RESULTS
(PROCESS_DATE,YEARMONTH,QUERY_NAME,STAT_RESULT)
VALUES
(
SYSDATE,202110,'TVPLUS_COUNT_ACT_STORE_MAU',9910);


;
SELECT * FROM TCMEYGI.STAT_RESULTS
WHERE  TO_DATE(PROCESS_DATE) = TO_DATE(SYSDATE)

;
-- HANGI SORGUNUN SONUCU GELMÝYOR-
select q.CREATE_DATE,q.query_name,q.DB_NAME,r.STAT_RESULT,r.day_id
from
(   SELECT *
    FROM (
        SELECT q.*, ROW_NUMBER() OVER (PARTITION BY QUERY_NAME ORDER BY CREATE_DATE DESC) ROW_NUM
        FROM REPORTER.DSS_AJANDA_QUERIES q )
        WHERE ROW_NUM = 1
            ) q , (
    SELECT * FROM TCMECETINER.STAT_RESULTS
    WHERE  TO_DATE(PROCESS_DATE) = TO_DATE(SYSDATE)
) r
where q.QUERY_NAME = r.QUERY_NAME(+)
AND r.STAT_RESULT IS NULL
AND q.DB_NAME in 'XDDS'
order by db_name desc,query_name
--AND q.QUERY_NAME LIKE '%90%' --OR q.QUERY_NAME LIKE '%90%'

;

SELECT * FROM TCMEYGI.STAT_RESULTS
WHERE  TO_DATE(PROCESS_DATE) = TO_DATE('18/09/2021','DD/MM/YYYY')
    AND QUERY_NAME LIKE 'FIZY%' --AND QUERY_NAME LIKE '%_MUSIC'
    AND YEARMONTH < 202109
order by 3 ASC, 2 DESC

;

UPDATE TCMEYGI.QUERIES SET PERIOD = 'D'  
WHERE QUERY_NAME ='FIZY_COUNT_SAMEDAY_CANCEL'
;
select * from TCMEYGI.QUERIES
WHERE QUERY_NAME ='FIZY_COUNT_SAMEDAY_CANCEL'
;
INSERT INTO TCMEYGI.STAT_RESULTS
(PROCESS_DATE,YEARMONTH,QUERY_NAME,STAT_RESULT)
VALUES
(
SYSDATE,202109,'LIFEBOX_COUNT_SAMEDAYCANCELLATION',2644);
;
select * from TCMEYGI.STAT_RESULTS
WHERE QUERY_NAME LIKE '%SAMEDAY%' and QUERY_NAME LIKE '%CANCEL%'
order by 1 desc