with cohort as(
SELECT 		c.SHORT_NAME KULUP, c.CLUSTERX TIER, c.CLUB_TYPE_NAME, a.YEARMONTH ACQ_MONTH, b.YEARMONTH RTN_MONTH,
            MONTHS_BETWEEN(B.DAY,A.DAY) MONTHS_DIFF, 
            FIRST_VALUE(COUNT(DISTINCT a.USER_ID)) OVER (PARTITION BY a.YEARMONTH, c.SHORT_NAME ORDER BY COUNT(DISTINCT a.USER_ID) DESC) ACQ_USER,
            COUNT(DISTINCT a.USER_ID) RETENT_USER,
			ROUND(COUNT(DISTINCT a.USER_ID) / 
				  FIRST_VALUE(COUNT(DISTINCT a.USER_ID)) OVER (PARTITION BY a.YEARMONTH, c.SHORT_NAME ORDER BY COUNT(DISTINCT a.USER_ID) DESC) * 100, 1) TUTUNMA_ORANI
FROM 		(
    --ACQ  (UCRETLI ABONELIK  IÇIN)
    SELECT 
        acq.YEARMONTH,acq.DAY,acq.USER_ID,acq.club_id
    FROM DWH.EOM_USERS acq
        LEFT JOIN DM.DIM_USER u on acq.user_ID = u.user_id
    WHERE 1=1 
        and acq.YEARMONTH between 202101 and 202209
        and acq.FREE_MEMBER_FLG = 0 -- 0: UCRETLI ABONELIK, 1:FREE ABONELIK
        and acq.COMMITMENT_TYPE = 'Annual'
        and u.IS_FOREIGNER = 0 -- Yerli
        AND not exists (SELECT 1 
                        FROM DWH.EOM_USERS b2 
                        where b2.yearmonth = TO_CHAR(ADD_MONTHS( to_date(acq.YEARMONTH,'YYYYMM'),-1),'YYYYMM') 
                            and b2.FREE_MEMBER_FLG = 0 -- 0: UCRETLI ABONELIK, 1:FREE ABONELIK
                            and b2.USER_ID = acq.USER_ID )
    GROUP BY acq.YEARMONTH,acq.DAY,acq.USER_ID,acq.club_id
    ORDER BY acq.YEARMONTH,acq.DAY,acq.USER_ID,acq.club_id
) a
LEFT JOIN  	dwh.EOM_USERS b
	ON 		a.USER_ID = b.USER_ID
LEFT JOIN 	dm.DIM_CLUB c 
	ON 		a.CLUB_ID = c.CLUB_ID 
WHERE 		a.YEARMONTH >= 202101
AND 		a.YEARMONTH <= b.YEARMONTH
--AND         c.SHORT_NAME = '001 Ist Kanyon'
GROUP BY 	c.SHORT_NAME , a.YEARMONTH,A.DAY, b.YEARMONTH, B.DAY, c.CLUSTERX, c.CLUB_TYPE_NAME
ORDER BY 	c.SHORT_NAME , a.YEARMONTH, b.YEARMONTH
)
select 
    co.*,
    LAG(co.TUTUNMA_ORANI,1) OVER(ORDER BY KULUP,ACQ_MONTH,RTN_MONTH) PREV_TUTUNMA_ORANI,
    LAG(co.TUTUNMA_ORANI,1) OVER(ORDER BY KULUP,ACQ_MONTH,RTN_MONTH) - co.TUTUNMA_ORANI CHURN_ORANI
from cohort co
ORDER BY KULUP,ACQ_MONTH,RTN_MONTH